# Generated by Django 5.2 on 2025-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Christ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotional',
            name='content',
            field=models.TextField(default='Full content coming soon'),
            preserve_default=False,
        ),
    ]
